# Generated by Django 3.0.5 on 2020-04-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_myuser_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_email', models.CharField(max_length=255)),
                ('from_email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='Books/pdf/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='Books/cover/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=255)),
                ('login_password', models.CharField(max_length=255)),
                ('login_email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255, null=True)),
                ('gst_no', models.CharField(max_length=256, null=True)),
                ('status', models.CharField(default='active', max_length=8)),
                ('created_date', models.DateField(null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('modified_date', models.DateField(null=True)),
                ('modified_by', models.IntegerField(null=True)),
                ('pin_code', models.CharField(max_length=255, null=True)),
                ('country', models.IntegerField(null=True)),
                ('state', models.IntegerField(null=True)),
                ('city', models.IntegerField(null=True)),
                ('landmark', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(null=True)),
            ],
        ),
    ]
