# Generated by Django 3.0.5 on 2020-04-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_adminemail_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_type_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
