# Generated by Django 3.0.5 on 2020-04-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_myuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_type_id',
            field=models.IntegerField(null=True),
        ),
    ]
