# Generated by Django 3.0.5 on 2020-04-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_myuserprofile_vendorlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_individual_vendor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='myuserprofile',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
