# Generated by Django 3.0.5 on 2020-04-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20200409_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_individual_vendor',
            field=models.IntegerField(default=0),
        ),
    ]
