# Generated by Django 3.0.5 on 2020-04-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20200409_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('state_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.IntegerField(null=True)),
                ('sortname', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=250, null=True)),
                ('phonecode', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('country_id', models.IntegerField(null=True)),
            ],
        ),
    ]
