# Generated by Django 3.0.5 on 2020-04-10 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20200409_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParlourService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, null=True)),
                ('service_duration', models.CharField(max_length=255, null=True)),
                ('service_price', models.FloatField(default=0.0, null=True)),
                ('service_material', models.TextField(null=True)),
                ('status', models.CharField(default='active', max_length=10)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('modified_date', models.DateField(null=True)),
                ('parlour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parlour', to='backend.Parlour')),
            ],
        ),
    ]
