# Generated by Django 3.0.5 on 2020-04-11 05:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_parlourservice'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='parlour',
            managers=[
                ('parman', django.db.models.manager.Manager()),
            ],
        ),
    ]
