# Generated by Django 3.0.5 on 2020-04-11 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20200411_0515'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='parlour',
            managers=[
            ],
        ),
    ]
