# Generated by Django 3.0.5 on 2020-04-11 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20200411_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='parlourservice',
            name='uuid',
            field=models.CharField(blank=True, default=uuid.UUID('0308ba29-5df1-4f6d-ba87-5bf1c3b2d75c'), max_length=100, null=True, unique=True),
        ),
    ]
