# Generated by Django 3.0.5 on 2020-04-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20200411_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parlourservice',
            name='uuid',
        ),
        migrations.AddField(
            model_name='parlourservice',
            name='uuid_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
