# Generated by Django 3.0.5 on 2020-04-11 14:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20200411_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parlourservice',
            name='uuid_code',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, null=True, unique=True),
        ),
    ]
