# Generated by Django 3.0.5 on 2020-04-11 15:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20200411_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='parlour',
            name='uuid_code',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='parlourservice',
            name='uuid_code',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
